---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hnikjcbg/cdn.hnikoloski.com
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R dist/css $DEPLOYPATH/css
    - /bin/cp -R dist/js $DEPLOYPATH/js
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    /bin/cp dist/index.html $DEPLOYPATH
  filters:
    - /dist/**
    - /dist/css/**
    - /dist/js/**
